version: "3"
services:
  app:
    container_name: docker-node
    restart: always
    build: ./server
    ports:
      - "80:5000"
    links:
      - react
      - mongo
  react:
    container_name: docker-react
    build: ./client
    ports:
      - "8080:3000"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
